sudo: false
language: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
  timeout: 3600
before_install:
- bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error
after_success: 
deploy:
  provider: releases
  api_key:
    secure: AXMBjbW7g80QpbgkX/+3d1FOUCDW51o8aKfE+PzurN8PMMZkc/RjDpI1absIIhpWvhWy56Ry+GJ2Fq2JsRTUMSS3p2QcmFs543DbkOCQe04QSBDPEadDV++g+EMmFS1AX+YmlKa/DJ+PS6zFvy6/+7HxhbK6MGK6woWQpdh2u0x9koeTripY1E/ofNkClplRY7fCU5DjDmBvqGH9sUysBxibLh8cO6391CYk+e/3hsbU+eLJDqtomrdUGlGTWAcoxevmImyhqj/kVyZKQUltjyZBqW/sPXmU390U6buQP9C8w21aA8BVrWNUEY6uh4uHRtLvP0+bCGYuElMoqU9kCcQZKrP5TrxamlILBsn/DiZVwuuSnAuH9nex8AV7LB6VNToRuKO4Xv5VDTtgobm3t936U1budwBuIWNcSV/WxMeNOKH/86nMzA1yY2VCRoBSEmDXZkXBRYcwgickUVnbrV/x2vsq/vWqJUBz5nZkJafzWbUbV5sQ8QSHaDt54pT/BnLZVBK89hirG42kaW5JqQy0q9YC/bojmSwJ7oNbkRoLpuCJuN4SOT2JYLVljXhYW65twcboh9IDWv4iZwlwPY6yFGeBkd0uh1OOIIcOPUBotL30PfORL/oDTPagt1T5R6AN7PknrjwzHsgnz5VHxu90YXWTqQ3hsXCyk1ANjR0=
  file: poster.pdf
  skip_cleanup: true
  on:
    repo: skulumani/2018_RD_poster
    tags: true
